#!/bin/bash

# TRADEMIND AI: AUTOMATED AWS WORKER SETUP SCRIPT (Hardened with Firebase Auth)
# This script installs Docker, clones the repo, configures the ENV, and launches the engine.

echo "--- TRADEMIND AI: INITIATING ENGINE ROOM SETUP ---"

# 1. System Update & Docker Installation
echo "[*] Installing Docker & Dependencies..."
sudo apt update && sudo apt upgrade -y
sudo apt install docker.io docker-compose git -y
sudo usermod -aG docker $USER

# 2. Repository Cloning
echo "[*] Cloning TradeMind AI Repository..."
if [ -d "TradeMindAI" ]; then
    cd TradeMindAI
    git pull origin main
else
    git clone https://github.com/lakshmistoresonline-afk/TradeMindAI.git
    cd TradeMindAI
fi

# 3. Environment Configuration
echo "[*] Configuring Production Environment..."
mkdir -p backend

# Production Firebase Credentials (BASE64 Encoded for resilience)
FIREBASE_CREDS_B64='ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAiY29tLXdlYmNyYWZ0LXRyYWRlbWluZGFpLWM4Zjc1IiwKICAicHJpdmF0ZV9rZXlfaWQiOiAiNWEyZWNiY2IxYTZmNzEzOTQ0Nzk1MDkzZjcyMDFkYWZjODFjMzFiZSIsCiAgInByaXZhdGVfa2V5IjogIi0tLS0tQkVHSU4gUFJJVkFURSBLRVktLS0tLVxuTUlJRXZnSUJBREFOQmdrcWhraUc5dzBCQVFFRkFBU0NCS2d3Z2dTa0FnRUFBb0lCQVFETUtNWnVrUE5PQkVJVlxuZ2czK0pPcWpubkwxd3lKUDFCWXRXcEJOckRUQ21vdlFpUEpseDZtcWRIYW8wTlJ0bTYvMXovZElCSjJDbWNmWlxuclhKdwFkMjBxYlRHQ0JxOXZIRlMwQmlCT3hJTXErRVBtc2R5QkdlWEwvcEtOaGV1eENxTjFENlhoMUZaeVZGVVxuK1d0WkYyTFBsSUN3akxpU0l6a0tIRS9IT1ZFMkR4aVFGcjFtTGVrS1RyQ2hLaUNVM3NZTDNVaXByRy8vdmEwblxuNnZYQ3llaExtZnJtQmgyc2VweU1SMkhtb3dqcHpINS9pUWhpdHdpMmkvVSszbTNWSFNvTkxOUlRNbFFtWjV4cFxuMnp1eDgxTzJQeGhVd2tIQWtrWUhCeFQ1bm9RUG5adDF0QWloWEIvMlFDaGhLb1JlT1ZMOERZUFZSSzJnQXlKMFxuM1VXMkFiU2pBZ01CQUFFQ2dnRUFBN3I5QVRreDBPdWYvMytjWE5mMDE1K0dEenFORG5OY0ltRUV3UDZVQ2poRFxudE1CRDJacy8zT2I2NGhQS3hlUHgzNlo0cUw2NDJCR1NSc1oyRUZvTHdJalhUa1VJcEEzazdqUHlOcTVMSXFNalxuWGlNZ1lOTjJ4eHJ2MGxwUnJYWlZKcmxKbVlBMSt0T0VZbTZhU1FyMTJjQW5aOUp5YnUwbzFpZjFSemtqWkQ3elxuQXcvQlNyYkdldmpOc1U4Zm16UnJMMytMSlhrNDRIOUFtbW8rMGFrckRFb2RRZWxMT3VsWHJCVDBEVTBiV25GS1xuOFJOVjBRTlBwVThERE1Va1hrRGF1U0FGMkdHTlVGYTdmRklGYkpXM0h2V1grS2NoNkxOMFBocHNiNUg3eFlUMFxuK1UxQmZodGF4aVVhK0JKcG9OcXhsekV2WW1YZU1ybGp4eDZ0YUdVcHRRS0JnUURxQ2dPNEpzUUNDR1R0UDdJVVxudlhXZ0g5dGZqR1I5ZngxaDBTY1FNSU9uQW1kTCtRN0ljNlFUemFKVHlYdEtKRVBqMjJZT0FmK25tb1ZIZTdPY1xua0R6aUdFOGNPM2ZCcG81TUc3TW1CdWRVancyTUczTWx5bGlLYVZuWWh2NGNWcFh4MHdhSVRQcmt2NGRYQnlrdFxuQVdpS09BaFdtSlVEWk9Hdjh1alh3T3hkRlFLQmdRRGZVUUFHaVhsQXZkN3VwWmpHS2ozR1JoRHplcCtnNWlTMVxuY2J2VWZUaFFsSVV4SElWYnppV2RTSnl3YktXZ3VhTStoOXZRRlFMcWl5aEZzdUVJeEZqMjFQWGg2QzljVkhFaVxuVk9PZmlHS0lkL1MrRnFsUGhsZDF6Zy9pKzVHd01YSUUzUmpjdGh2K0VybmN3RGQ5eVNIc3o5TjA4U3NhQkgzTVxublFIa1JMTm8xd0tCZ1FDS3ordkswcnRaRlU5L1pGTWtPbGZzNUZoQ1FNdnRuM0oyN1EzRlRYRVlvcFZQKzJYb1xuUUthbDFFYWVlWmQxcnpMUk4vVTlBN1IxM1hHRnAzb3R0Mk5WR3VQNU05QmcvSC9UNW00SWRQbktMcHJ6YWVpUFxuRm9nVGVFOEEzWGhrcUhxQkZ3LzkwZUxSd0VQdXUyR1J2dzhaUkFpMkRBUCtJbHkxOWxaaWVadjN6UUtCZ0JkclxuYmo1QlFwY1lrbjJpbmtBQ0JCSjhIS0Q4Tml0d2wxN3orNGZRVGd5ZFZzNk11Q3VsbGVwRnlERDBZL1pVSVp1WVxuTWVSRG45ZXJHbUVjM2w3R0FMSjZLUU0xRDJwMmJKcjJIaDBIOTVWcVJ4OThUdXRKSW5qM1VGRTBvdFhBaWIyYVxuMWxXblA0NUl0bmRCTFZDaXZFMFNpcEdVRFRvZ1NIVWg3aVhiVXBsbkFvR0JBTGZHUGJuNWFva2oyTndjby9TTVxuZm9hVE9CcDhBTWRDbFBVSmVXdURBd2x1ekpJcmlaeDJ2c1NXcEgvQTE1Y3NhLy9yR2xjZFBCOTBxdjJyeEFPN1xuRzFETlZTeG9xcDVGa0trcXFRaWdHcDBKSzFlZGNMRndaR3N1dkIxTzNpRVE2Wk9vWnhBVi9iQy9tRTFGYU9mWlxudldTUm1OSUoyWGhtbmU4c1JJb1FOT0s2XG4tLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tXG4iLAogICJjbGllbnRfZW1haWwiOiAiZmlyZWJhc2UtYWRtaW5zZGstZmJzdmNAY29tLXdlYmNyYWZ0LXRyYWRlbWluZGFpLWM4Zjc1LmlhbS5nc2VydmljZWFjY291bnQuY29tIiwKICAiY2xpZW50X2lkIjogIjEwNDU5MDExNzY1NTQyNjY4NzI4MCIsCiAgImF1dGhfdXJpIjogImh0dHBzOi8vYWNjb3VudHMuZ29vZ2xlLmNvbS9vL29hdXRoMi9hdXRoIiwKICAidG9rZW5fdXJpIjogImh0dHBzOi8vb2F1dGgyLmdvb2dsZWFwaXMuY29tL3Rva2VuIiwKICAiYXV0aF9wcm92aWRlcl94NTA5X2NlcnRfdXJsIjogImh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL29hdXRoMi92MS9jZXJ0cyIsCiAgImNsaWVudF94NTA5X2NlcnRfdXJsIjogImh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL3JvYm90L3YxL21ldGFkYXRhL3g1MDkvZmlyZWJhc2UtYWRtaW5zZGstZmJzdmMlNDBjb20td2ViY3JhZnQtdHJhZGVtaW5kYWktYzhmNzUuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLAogICJ1bml2ZXJzZV9kb21haW4iOiAiZ29vZ2xlYXBpcy5jb20iCn0K'

cat <<EOF > backend/.env
PROJECT_NAME="TradeMind AI"
REDIS_URL="redis://redis:6379/0"
SECRET_KEY="your-super-secret-key"
ALGORITHM="HS256"
ACCESS_TOKEN_EXPIRE_MINUTES=30

FIREBASE_PROJECT_ID="com-webcraft-trademindai-c8f75"
FIREBASE_SERVICE_ACCOUNT='$FIREBASE_CREDS_B64'
POSTGRES_URL="postgresql://neondb_owner:npg_L5GbM3HeYfry@ep-fancy-mountain-axa35p28-pooler.c-4.us-east-2.aws.neon.tech/neondb?sslmode=require"
GROQ_API_KEY="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"

MARKET_DATA_PROVIDER="groww"
EOF

# 4. Launching Workers
echo "[*] Launching TradeMind Workers via Docker..."
sudo docker-compose -f docker-compose.workers.yml up --build -d

echo "--- SETUP RE-SYNCHRONIZED ---"
echo "[!] Monitor logs with: docker logs -f trademindai-worker-1"
