/**
 * NIFTY-200 Company Name Dictionary
 * Guarantees proper corporate naming for all 200 constituents across all dashboard cards.
 */

export const COMPANY_NAMES: Record<string, string> = {
  'ABB': 'ABB India Limited',
  'ACC': 'ACC Limited',
  'ADANIENSOL': 'Adani Energy Solutions Limited',
  'ADANIENT': 'Adani Enterprises Limited',
  'ADANIGREEN': 'Adani Green Energy Limited',
  'ADANIPORTS': 'Adani Ports and Special Economic Zone Limited',
  'ADANIPOWER': 'Adani Power Limited',
  'ATGL': 'Adani Total Gas Limited',
  'AMBUJACEM': 'Ambuja Cements Limited',
  'APOLLOHOSP': 'Apollo Hospitals Enterprise Limited',
  'APOLLOTYRE': 'Apollo Tyres Limited',
  'ASHOKLEY': 'Ashok Leyland Limited',
  'ASIANPAINT': 'Asian Paints Limited',
  'ASTRAL': 'Astral Limited',
  'AUROPHARMA': 'Aurobindo Pharma Limited',
  'AXISBANK': 'Axis Bank Limited',
  'BAJAJ-AUTO': 'Bajaj Auto Limited',
  'BAJAJFINSV': 'Bajaj Finserv Limited',
  'BAJFINANCE': 'Bajaj Finance Limited',
  'BAJAJHLDNG': 'Bajaj Holdings & Investment Limited',
  'BALKRISIND': 'Balkrishna Industries Limited',
  'BANDHANBNK': 'Bandhan Bank Limited',
  'BANKBARODA': 'Bank of Baroda',
  'BANKINDIA': 'Bank of India',
  'BATAINDIA': 'Bata India Limited',
  'BEL': 'Bharat Electronics Limited',
  'BERGEPAINT': 'Berger Paints India Limited',
  'BHARATFORG': 'Bharat Forge Limited',
  'BHEL': 'Bharat Heavy Electricals Limited',
  'BHARTIARTL': 'Bharti Airtel Limited',
  'BIOCON': 'Biocon Limited',
  'BLUEDART': 'Blue Dart Express Limited',
  'BOSCHLTD': 'Bosch Limited',
  'BPCL': 'Bharat Petroleum Corporation Limited',
  'BRITANNIA': 'Britannia Industries Limited',
  'CANBK': 'Canara Bank',
  'CANFINHOME': 'Can Fin Homes Limited',
  'CGPOWER': 'CG Power and Industrial Solutions Limited',
  'CHAMBLFERT': 'Chambal Fertilisers and Chemicals Limited',
  'CHOLAFIN': 'Cholamandalam Investment and Finance Company Limited',
  'CIPLA': 'Cipla Limited',
  'COALINDIA': 'Coal India Limited',
  'COFORGE': 'Coforge Limited',
  'COLPAL': 'Colgate-Palmolive (India) Limited',
  'CONCOR': 'Container Corporation of India Limited',
  'COROMANDEL': 'Coromandel International Limited',
  'CROMPTON': 'Crompton Greaves Consumer Electricals Limited',
  'CUMMINSIND': 'Cummins India Limited',
  'DABUR': 'Dabur India Limited',
  'DALBHARAT': 'Dalmia Bharat Limited',
  'DEEPAKNTR': 'Deepak Nitrite Limited',
  'DELHIVERY': 'Delhivery Limited',
  'DIVISLAB': "Divi's Laboratories Limited",
  'DIXON': 'Dixon Technologies (India) Limited',
  'DLF': 'DLF Limited',
  'DRREDDY': "Dr. Reddy's Laboratories Limited",
  'EICHERMOT': 'Eicher Motors Limited',
  'ESCORTS': 'Escorts Kubota Limited',
  'EXIDEIND': 'Exide Industries Limited',
  'FEDERALBNK': 'The Federal Bank Limited',
  'FORTIS': 'Fortis Healthcare Limited',
  'GAIL': 'GAIL (India) Limited',
  'GLENMARK': 'Glenmark Pharmaceuticals Limited',
  'GMRINFRA': 'GMR Airports Infrastructure Limited',
  'GODREJCP': 'Godrej Consumer Products Limited',
  'GODREJPROP': 'Godrej Properties Limited',
  'GRASIM': 'Grasim Industries Limited',
  'GUJGASLTD': 'Gujarat Gas Limited',
  'HAL': 'Hindustan Aeronautics Limited',
  'HAVELLS': 'Havells India Limited',
  'HCLTECH': 'HCL Technologies Limited',
  'HDFCBANK': 'HDFC Bank Limited',
  'HDFCLIFE': 'HDFC Life Insurance Company Limited',
  'HEROMOTOCO': 'Hero MotoCorp Limited',
  'HINDALCO': 'Hindalco Industries Limited',
  'HINDCOPPER': 'Hindustan Copper Limited',
  'HINDPETRO': 'Hindustan Petroleum Corporation Limited',
  'HINDUNILVR': 'Hindustan Unilever Limited',
  'HINDZINC': 'Hindustan Zinc Limited',
  'HUDCO': 'Housing & Urban Development Corporation Limited',
  'ICICIBANK': 'ICICI Bank Limited',
  'ICICIGI': 'ICICI Lombard General Insurance Company Limited',
  'ICICIPRULI': 'ICICI Prudential Life Insurance Company Limited',
  'IDBI': 'IDBI Bank Limited',
  'IDFCFIRSTB': 'IDFC FIRST Bank Limited',
  'IGL': 'Indraprastha Gas Limited',
  'INDHOTEL': 'The Indian Hotels Company Limited',
  'INDIAMART': 'IndiaMART InterMESH Limited',
  'INDIANB': 'Indian Bank',
  'INDIGO': 'InterGlobe Aviation Limited (IndiGo)',
  'INDUSINDBK': 'IndusInd Bank Limited',
  'INDUSTOWER': 'Indus Towers Limited',
  'INFY': 'Infosys Limited',
  'IOC': 'Indian Oil Corporation Limited',
  'IRB': 'IRB Infrastructure Developers Limited',
  'IRCTC': 'Indian Railway Catering and Tourism Corporation Limited',
  'IRFC': 'Indian Railway Finance Corporation Limited',
  'ITC': 'ITC Limited',
  'JINDALSTEL': 'Jindal Steel & Power Limited',
  'JSWENERGY': 'JSW Energy Limited',
  'JSWSTEEL': 'JSW Steel Limited',
  'JUBLFOOD': 'Jubilant FoodWorks Limited',
  'KALYANKJIL': 'Kalyan Jewellers India Limited',
  'KANSAINER': 'Kansai Nerolac Paints Limited',
  'KARURVYSYA': 'Karur Vysya Bank Limited',
  'KEI': 'KEI Industries Limited',
  'KOTAKBANK': 'Kotak Mahindra Bank Limited',
  'KPITTECH': 'KPIT Technologies Limited',
  'L&TFH': 'L&T Finance Holdings Limited',
  'LICI': 'Life Insurance Corporation of India',
  'LICHSGFIN': 'LIC Housing Finance Limited',
  'LTIM': 'LTIMindtree Limited',
  'LT': 'Larsen & Toubro Limited',
  'LUPIN': 'Lupin Limited',
  'M&MFIN': 'Mahindra & Mahindra Financial Services Limited',
  'M&M': 'Mahindra & Mahindra Limited',
  'MAHABANK': 'Bank of Maharashtra',
  'MANAPPURAM': 'Manappuram Finance Limited',
  'MARICO': 'Marico Limited',
  'MARUTI': 'Maruti Suzuki India Limited',
  'MAXHEALTH': 'Max Healthcare Institute Limited',
  'MAZDOCK': 'Mazagon Dock Shipbuilders Limited',
  'MFSL': 'Max Financial Services Limited',
  'MGL': 'Mahanagar Gas Limited',
  'MPHASIS': 'Mphasis Limited',
  'MRF': 'MRF Limited',
  'MUTHOOTFIN': 'Muthoot Finance Limited',
  'NATIONALUM': 'National Aluminium Company Limited',
  'NAVINFLUOR': 'Navin Fluorine International Limited',
  'NESTLEIND': 'Nestle India Limited',
  'NHPC': 'NHPC Limited',
  'NMDC': 'NMDC Limited',
  'NTPC': 'NTPC Limited',
  'NYKAA': 'FSN E-Commerce Ventures Limited (Nykaa)',
  'OBEROIRLTY': 'Oberoi Realty Limited',
  'ONGC': 'Oil & Natural Gas Corporation Limited',
  'OIL': 'Oil India Limited',
  'PAGEIND': 'Page Industries Limited',
  'PATANJALI': 'Patanjali Foods Limited',
  'PAYTM': 'One97 Communications Limited (Paytm)',
  'PEL': 'Piramal Enterprises Limited',
  'PERSISTENT': 'Persistent Systems Limited',
  'PETRONET': 'Petronet LNG Limited',
  'PFC': 'Power Finance Corporation Limited',
  'PHOENIXLTD': 'The Phoenix Mills Limited',
  'PIDILITIND': 'Pidilite Industries Limited',
  'PIIND': 'PI Industries Limited',
  'PNB': 'Punjab National Bank',
  'POLYCAB': 'Polycab India Limited',
  'POONAWALLA': 'Poonawalla Fincorp Limited',
  'POWERGRID': 'Power Grid Corporation of India Limited',
  'PRESTIGE': 'Prestige Estates Projects Limited',
  'PVRINOX': 'PVR INOX Limited',
  'RADICO': 'Radico Khaitan Limited',
  'RVNL': 'Rail Vikas Nigam Limited',
  'RECLTD': 'REC Limited',
  'RELIANCE': 'Reliance Industries Limited',
  'SAIL': 'Steel Authority of India Limited',
  'SBICARD': 'SBI Cards and Payment Services Limited',
  'SBILIFE': 'SBI Life Insurance Company Limited',
  'SBIN': 'State Bank of India',
  'SHREECEM': 'Shree Cement Limited',
  'SHRIRAMFIN': 'Shriram Finance Limited',
  'SIEMENS': 'Siemens Limited',
  'SJVN': 'SJVN Limited',
  'SKFINDIA': 'SKF India Limited',
  'SONACOMS': 'Sona BLW Precision Forgings Limited',
  'SRF': 'SRF Limited',
  'SUNPHARMA': 'Sun Pharmaceutical Industries Limited',
  'SUNTV': 'Sun TV Network Limited',
  'SUPREMEIND': 'Supreme Industries Limited',
  'SUZLON': 'Suzlon Energy Limited',
  'SYNGENE': 'Syngene International Limited',
  'TATACOMM': 'Tata Communications Limited',
  'TATACONSUM': 'Tata Consumer Products Limited',
  'TATAELXSI': 'Tata Elxsi Limited',
  'TATAMOTORS': 'Tata Motors Limited',
  'TATAPOWER': 'Tata Power Company Limited',
  'TATASTEEL': 'Tata Steel Limited',
  'TCS': 'Tata Consultancy Services Limited',
  'TECHM': 'Tech Mahindra Limited',
  'TITAN': 'Titan Company Limited',
  'TORNTPHARM': 'Torrent Pharmaceuticals Limited',
  'TORNTPOWER': 'Torrent Power Limited',
  'TRENT': 'Trent Limited',
  'TRIDENT': 'Trident Limited',
  'TIINDIA': 'Tube Investments of India Limited',
  'UBL': 'United Breweries Limited',
  'UCOBANK': 'UCO Bank',
  'ULTRACEMCO': 'UltraTech Cement Limited',
  'UNIONBANK': 'Union Bank of India',
  'UNITDSPR': 'United Spirits Limited',
  'VBL': 'Varun Beverages Limited',
  'VEDL': 'Vedanta Limited',
  'VOLTAS': 'Voltas Limited',
  'WHIRLPOOL': 'Whirlpool of India Limited',
  'WIPRO': 'Wipro Limited',
  'YESBANK': 'Yes Bank Limited',
  'ZOMATO': 'Zomato Limited',
  'ZYDUSLIFE': 'Zydus Lifesciences Limited'
};

export function getCompanyName(symbol: string): string {
  if (!symbol) return 'INSTRUMENT';
  const cleanSym = symbol.toUpperCase().trim();
  return COMPANY_NAMES[cleanSym] || `${cleanSym} Limited`;
}
