# Canonical NIFTY 200 Constituent Universe
<<<<<<< HEAD
# Source: NSE India (Refined for TradeMind AI P0 - Exactly 200 Symbols)
# Updated: 2026-08-16

NIFTY_200_CONSTITUENTS = [
    "ABB", "ACC", "ADANIENSOL", "ADANIENT", "ADANIGREEN", "ADANIPORTS", "ADANIPOWER", "ATGL", "AMBUJACEM", "APOLLOHOSP",
    "APOLLOTYRE", "ASHOKLEY", "ASIANPAINT", "ASTRAL", "AUROPHARMA", "AXISBANK", "BAJAJ-AUTO", "BAJAJFINSV", "BAJFINANCE",
    "BAJAJHLDNG", "BALKRISIND", "BANDHANBNK", "BANKBARODA", "BANKINDIA", "BATAINDIA", "BEL", "BERGEPAINT", "BHARATFORG", "BHEL",
    "BHARTIARTL", "BIOCON", "BLUEDART", "BOSCHLTD", "BPCL", "BRITANNIA", "CANBK", "CANFINHOME",
    "CGPOWER", "CHAMBLFERT", "CHOLAFIN", "CIPLA", "COALINDIA", "COFORGE", "COLPAL", "CONCOR", "COROMANDEL", "CROMPTON",
    "CUMMINSIND", "DABUR", "DALBHARAT", "DEEPAKNTR", "DELHIVERY", "DIVISLAB", "DIXON", "DLF", "DRREDDY",
    "EICHERMOT", "ESCORTS", "EXIDEIND", "FEDERALBNK", "FORTIS", "GAIL", "GLENMARK", "GMRINFRA", "GODREJCP",
    "GODREJPROP", "GRASIM", "GUJGASLTD", "HAL", "HAVELLS", "HCLTECH", "HDFCBANK", "HDFCLIFE", "HEROMOTOCO", "HINDALCO",
    "HINDCOPPER", "HINDPETRO", "HINDUNILVR", "HINDZINC", "HUDCO", "ICICIBANK", "ICICIGI", "ICICIPRULI", "IDBI", "IDFCFIRSTB",
    "IGL", "INDHOTEL", "INDIAMART", "INDIANB", "INDIGO", "INDUSINDBK", "INDUSTOWER", "INFY", "IOC",
    "IRB", "IRCTC", "IRFC", "ITC", "JINDALSTEL", "JSWENERGY", "JSWSTEEL", "JUBLFOOD", "KALYANKJIL",
    "KANSAINER", "KARURVYSYA", "KEI", "KOTAKBANK", "KPITTECH", "L&TFH", "LICI", "LICHSGFIN", "LTIM",
    "LT", "LUPIN", "M&MFIN", "M&M", "MAHABANK", "MANAPPURAM", "MARICO", "MARUTI", "MAXHEALTH", "MAZDOCK",
    "MFSL", "MGL", "MPHASIS", "MRF", "MUTHOOTFIN", "NATIONALUM", "NAVINFLUOR", "NESTLEIND", "NHPC",
    "NMDC", "NTPC", "NYKAA", "OBEROIRLTY", "ONGC", "OIL", "PAGEIND", "PATANJALI", "PAYTM", "PEL",
    "PERSISTENT", "PETRONET", "PFC", "PHOENIXLTD", "PIDILITIND", "PIIND", "PNB", "POLYCAB", "POONAWALLA", "POWERGRID",
    "PRESTIGE", "PVRINOX", "RADICO", "RVNL", "RECLTD", "RELIANCE", "SAIL", "SBICARD", "SBILIFE",
    "SBIN", "SHREECEM", "SHRIRAMFIN", "SIEMENS", "SJVN", "SKFINDIA", "SONACOMS", "SRF", "SUNPHARMA", "SUNTV",
    "SUPREMEIND", "SUZLON", "SYNGENE", "TATACOMM", "TATACONSUM", "TATAELXSI", "TATAMOTORS", "TATAPOWER", "TATASTEEL",
=======
# Source: NSE India (Representative as of Aug 2024)

NIFTY_200_CONSTITUENTS = [
    "ABB", "ACC", "ADANIENSOL", "ADANIENT", "ADANIGREEN", "ADANIPORTS", "ADANIPOWER", "ATGL", "AMBUJACEM", "APOLLOHOSP",
    "APOLLOTYRE", "ASHOKLEY", "ASIANPAINT", "ASTRAL", "AUROPHARMA", "AVANTIFEED", "AXISBANK", "BAJAJ-AUTO", "BAJAJFINSV", "BAJFINANCE",
    "BAJAJHLDNG", "BALKRISIND", "BANDHANBNK", "BANKBARODA", "BANKINDIA", "BATAINDIA", "BEL", "BERGEPAINT", "BHARATFORG", "BHEL",
    "BHARTIARTL", "BIOCON", "BIRLACORPN", "BLUEDART", "BOSCHLTD", "BPCL", "BRITANNIA", "BSOFT", "CANBK", "CANFINHOME",
    "CGPOWER", "CHAMBLFERT", "CHOLAFIN", "CIPLA", "COALINDIA", "COFORGE", "COLPAL", "CONCOR", "COROMANDEL", "CROMPTON",
    "CUMMINSIND", "CYIENT", "DABUR", "DALBHARAT", "DEEPAKNTR", "DELHIVERY", "DIVISLAB", "DIXON", "DLF", "DRREDDY",
    "EICHERMOT", "ESCORTS", "EXIDEIND", "FEDERALBNK", "FORTIS", "GAIL", "GLENMARK", "GMMPFAUDLR", "GMRINFRA", "GODREJCP",
    "GODREJPROP", "GRASIM", "GUJGASLTD", "HAL", "HAVELLS", "HCLTECH", "HDFCBANK", "HDFCLIFE", "HEROMOTOCO", "HINDALCO",
    "HINDCOPPER", "HINDPETRO", "HINDUNILVR", "HINDZINC", "HUDCO", "ICICIBANK", "ICICIGI", "ICICIPRULI", "IDBI", "IDFCFIRSTB",
    "IEX", "IGL", "INDHOTEL", "INDIAMART", "INDIANB", "INDIGO", "INDUSINDBK", "INDUSTOWER", "INFY", "IOC",
    "IPCALAB", "IRB", "IRCTC", "IRFC", "ITC", "JINDALSTEL", "JSWENERGY", "JSWSTEEL", "JUBLFOOD", "KALYANKJIL",
    "KANSAINER", "KARURVYSYA", "KEC", "KEI", "KOTAKBANK", "KPITTECH", "L&TFH", "LICI", "LICHSGFIN", "LTIM",
    "LT", "LUPIN", "M&MFIN", "M&M", "MAHABANK", "MANAPPURAM", "MARICO", "MARUTI", "MAXHEALTH", "MAZDOCK",
    "METROPOLIS", "MFSL", "MGL", "MPHASIS", "MRF", "MUTHOOTFIN", "NATIONALUM", "NAVINFLUOR", "NESTLEIND", "NHPC",
    "NMDC", "NTPC", "NYKAA", "OBEROIRLTY", "ONGC", "OIL", "PAGEIND", "PATANJALI", "PAYTM", "PEL",
    "PERSISTENT", "PETRONET", "PFC", "PHOENIXLTD", "PIDILITIND", "PIIND", "PNB", "POLYCAB", "POONAWALLA", "POWERGRID",
    "PRESTIGE", "PVRINOX", "QUESS", "RADICO", "RVNL", "RECLTD", "RELIANCE", "SAIL", "SBICARD", "SBILIFE",
    "SBIN", "SHREECEM", "SHRIRAMFIN", "SIEMENS", "SJVN", "SKFINDIA", "SONACOMS", "SRF", "SUNPHARMA", "SUNTV",
    "SUPREMEIND", "SUZLON", "SYNGENE", "TATACOMM", "TATACONSUM", "TATAELXSI", "TATAMOTORS", "TATAPOWER", "TATASTEEL", "TATASTEEL",
>>>>>>> origin/main
    "TCS", "TECHM", "TITAN", "TORNTPHARM", "TORNTPOWER", "TRENT", "TRIDENT", "TIINDIA", "UBL", "UCOBANK",
    "ULTRACEMCO", "UNIONBANK", "UNITDSPR", "VBL", "VEDL", "VOLTAS", "WHIRLPOOL", "WIPRO", "YESBANK", "ZOMATO",
    "ZYDUSLIFE"
]

# Ensure uniqueness and sorted order
NIFTY_200_CONSTITUENTS = sorted(list(set(NIFTY_200_CONSTITUENTS)))

def get_nifty200():
    return NIFTY_200_CONSTITUENTS
<<<<<<< HEAD

if __name__ == "__main__":
    print(f"NIFTY 200 UNIVERSE: {len(NIFTY_200_CONSTITUENTS)} unique symbols.")
=======
>>>>>>> origin/main
