import os
import sys
import argparse
from sqlalchemy import text
from dotenv import load_dotenv

# Add project root to path
sys.path.append(os.path.abspath(os.path.join(os.getcwd(), '.')))
load_dotenv('backend/.env')

from backend.core.postgres import engine, SessionLocal, LiveSignalDB, PredictionDB, OpportunityDB

def cleanup(dry_run=True, confirm=False):
    print(f"[*] TradeMind AI - Data Forensic Cleanup (DRY_RUN={dry_run})")

    if not dry_run and not confirm:
        print("[!] ERROR: Explicit --confirm required for production deletion.")
        return

    with engine.connect() as conn:
        # 1. PURGE SYNTHETIC SIGNALS
        # Signals starting with 'master_', 'audit_', 'hist_', 'fno_', 'live_opt_', 'live_fut_', 'live_eq_' are all generated by manual scripts.
        prefixes = ['master_', 'audit_', 'hist_', 'fno_', 'live_opt_', 'live_fut_', 'live_eq_']

        print("\n[*] Auditing signal records for synthetic origin...")
        for prefix in prefixes:
            count_query = text(f"SELECT count(*) FROM live_signals WHERE id LIKE '{prefix}%'")
            count = conn.execute(count_query).scalar()
            print(f"   Prefix '{prefix}': {count} records found.")

            if not dry_run and count > 0:
                delete_query = text(f"DELETE FROM live_signals WHERE id LIKE '{prefix}%'")
                conn.execute(delete_query)
                print(f"   [+] Purged {count} records.")

        # 2. PURGE OBSOLETE OPPORTUNITIES (AI GENERATED FLUFF)
        print("\n[*] Auditing opportunity scanner (Opportunities table)...")
        count = conn.execute(text("SELECT count(*) FROM opportunities")).scalar()
        print(f"   Total Opportunities: {count}")
        if not dry_run and count > 0:
            conn.execute(text("DELETE FROM opportunities"))
            print(f"   [+] Purged {count} opportunities.")

        # 3. PURGE OLD PREDICTIONS (ML ARTIFACTS)
        print("\n[*] Auditing ML predictions (Inference history)...")
        count = conn.execute(text("SELECT count(*) FROM predictions")).scalar()
        print(f"   Total Predictions: {count}")
        if not dry_run and count > 0:
            conn.execute(text("DELETE FROM predictions"))
            print(f"   [+] Purged {count} predictions.")

        # 4. FIX CORRUPT MASTER DATA
        print("\n[*] Identifying orphaned or corrupted stock master records...")
        corrupt_names = ['Data Corrupted', 'Unknown']
        for name in corrupt_names:
            count = conn.execute(text(f"SELECT count(*) FROM stocks WHERE name = '{name}'")).scalar()
            print(f"   Corrupt '{name}': {count} records found.")
            if not dry_run and count > 0:
                conn.execute(text(f"DELETE FROM stocks WHERE name = '{name}'"))
                print(f"   [+] Removed {count} records.")

        if not dry_run:
            conn.commit()
            print("\n[SUCCESS] Production data nodes have been forensically cleaned.")
        else:
            print("\n[INFO] Dry run complete. No changes were made to the Neon database.")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="TradeMind AI Data Cleanup Tool")
    parser.add_argument("--dry-run", action="store_true", default=True, help="Perform audit without deleting data (default)")
    parser.add_argument("--confirm", action="store_true", help="Confirm production deletion")
    parser.add_argument("--no-dry-run", action="store_false", dest="dry_run", help="Disable dry run mode")

    args = parser.parse_args()
    cleanup(dry_run=args.dry_run, confirm=args.confirm)
