from fastapi import APIRouter, Depends, HTTPException, Query
from typing import List, Dict, Any, Optional
from backend.core.container import container
from backend.core.auth import get_current_user
from backend.domain.models.ios import WorkspaceState, ResearchNote, MarketRegime, MarketOpportunity, MarketIntelligenceReport, TradeFeedback
import uuid
import datetime

router = APIRouter()

@router.get("/regime", response_model=MarketRegime)
async def get_market_regime():
    """
    Returns the current Market Regime (Bull/Bear/Sideways) detected by institutional bias models.
    """
    regime = await container.ios_repo.get_latest_regime()
    if not regime:
        # Fallback for empty DB (RC-2 Safe)
        return MarketRegime(
            date=datetime.datetime.utcnow(), regime="SIDEWAYS", risk_mode="NEUTRAL",
            sentiment_score=0.5, volatility_index=15.0,
            description="Market analysis currently in progress. Initializing regime detection..."
        )
    return regime

@router.get("/opportunities", response_model=List[MarketOpportunity])
async def get_opportunities(limit: int = 10):
    """
    Lists high-conviction market opportunities (Breakouts, Reversals, etc.) generated by the AI Opportunity Engine.
    """
    return await container.ios_repo.get_active_opportunities(limit=limit)

@router.get("/intel", response_model=MarketIntelligenceReport)
async def get_market_intelligence(type: str = "CLOSING"):
    """
    Fetches daily institutional intelligence reports (Morning Brief, Closing Report).
    """
    report = await container.ios_repo.get_latest_intel_report(type)
    if not report:
        # Fallback for empty DB (RC-2 Safe)
        return MarketIntelligenceReport(
            id="initial", type=type, date=datetime.datetime.utcnow(),
            summary="Market Intelligence Engine initialized. Calculating institutional bias for latest session...",
            key_events=["Data Ingestion Active"], top_movers=[], sector_performance={}, ai_bias="NEUTRAL"
        )
    return report

@router.post("/intel/trigger")
async def trigger_market_intel():
    """
    Vision 2.0: Manually triggers the Daily Market Intelligence processing.
    Populates regimes, opportunities and closing reports.
    """
    from backend.workers.tasks import process_market_intelligence
    task = process_market_intelligence.delay()
    return {"message": "Market Intelligence processing triggered", "task_id": task.id}

@router.get("/graph/{symbol}")
async def get_knowledge_graph(symbol: str):
    """
    Generates a semantic knowledge graph for a symbol, mapping its peers, sector, and institutional dependencies.
    """
    return await container.graph_service.get_stock_relations(symbol)

@router.get("/twin/{symbol}")
async def get_digital_twin(symbol: str):
    """
    Retrieves the Digital Twin profile of a stock: a real-time unified identity of technical, fundamental, and AI states.
    """
    return await container.twin_service.get_stock_twin(symbol)

@router.get("/alignment/{symbol}")
async def get_mtf_alignment(symbol: str):
    """
    Analyzes Multi-Timeframe Alignment (1H, Daily, Weekly) to detect institutional trend coordination.
    """
    return await container.timeframe_service.analyze_alignment(symbol)

@router.get("/similarity/{symbol}")
async def get_similar_patterns(symbol: str):
    """
    Vision 2.0: AI Similarity Engine.
    Scans historical data to find similar technical and regime structures.
    """
    return await container.feature_store.find_similar_patterns(symbol)

@router.get("/notes/{symbol}", response_model=List[ResearchNote])
async def get_research_notes(symbol: str, current_user: dict = Depends(get_current_user)):
    return await container.ios_repo.get_stock_notes(current_user["uid"], symbol)

@router.post("/notes")
async def create_research_note(note_data: Dict[str, Any], current_user: dict = Depends(get_current_user)):
    note = ResearchNote(
        id=str(uuid.uuid4()),
        user_id=current_user["uid"],
        symbol=note_data["symbol"],
        content=note_data["content"],
        tags=note_data.get("tags", [])
    )
    await container.ios_repo.save_research_note(note)
    return note

@router.get("/workspaces", response_model=List[WorkspaceState])
async def get_workspaces(current_user: dict = Depends(get_current_user)):
    return await container.ios_repo.get_user_workspaces(current_user["uid"])

@router.post("/workspaces")
async def save_workspace(workspace: WorkspaceState, current_user: dict = Depends(get_current_user)):
    workspace.user_id = current_user["uid"]
    await container.ios_repo.save_workspace(workspace)
    return workspace

@router.get("/journal", response_model=List[TradeFeedback])
async def get_trade_journal(current_user: dict = Depends(get_current_user)):
    """
    Vision 2.0: AI Trade Coach & Journal.
    Retrieves all historical trades and AI mentorship feedback.
    """
    return await container.ios_repo.get_user_trades(current_user["uid"])

@router.post("/journal")
async def add_trade_to_journal(trade_data: Dict[str, Any], current_user: dict = Depends(get_current_user)):
    """
    Vision 2.0: AI Trade Coach.
    Analyzes a new trade execution and provides instant feedback.
    """
    # 1. Fetch AI Sentiment at entry date (Simplified for demo)
    ai_score = 75.0

    # 2. Generate Feedback via Coach Service
    feedback = container.coach_service.generate_feedback({
        **trade_data,
        "user_id": current_user["uid"],
        "entry_date": datetime.datetime.fromisoformat(trade_data["entry_date"]),
        "exit_date": datetime.datetime.fromisoformat(trade_data["exit_date"])
    }, ai_score)

    # 3. Persist
    await container.ios_repo.save_trade_feedback(feedback)
    return feedback

@router.get("/portfolio/optimize")
async def get_portfolio_optimizations(current_user: dict = Depends(get_current_user)):
    """
    Vision 2.0: Active AI Portfolio Rebalancing.
    """
    # 1. Fetch current portfolio holdings (Integration with Paper Trading / Real broker)
    # Placeholder: getting all stocks for now to simulate logic
    stocks = await container.repository.get_all_stocks(limit=10)

    # 2. Get Regime for bias context
    regime = await container.ios_repo.get_latest_regime()
    bias = regime.regime if regime else "SIDEWAYS"

    # 3. Generate suggestions
    from backend.services.ios.portfolio_manager import AIPortfolioManager
    return AIPortfolioManager.get_rebalancing_suggestions(stocks, bias)

@router.get("/api-keys")
async def get_api_keys(current_user: dict = Depends(get_current_user)):
    docs = container.ios_repo.db.collection("api_keys").where("user_id", "==", current_user["uid"]).stream()
    return [doc.to_dict() for doc in docs]

@router.post("/api-keys")
async def generate_api_key(current_user: dict = Depends(get_current_user)):
    key = f"tm_{uuid.uuid4().hex}"
    key_data = {
        "id": str(uuid.uuid4()),
        "user_id": current_user["uid"],
        "key_prefix": key[:8] + "...",
        "full_key": key, # In real prod, hash this!
        "created_at": datetime.datetime.utcnow(),
        "name": "Default API Key"
    }
    container.ios_repo.db.collection("api_keys").document(key_data["id"]).set(key_data)
    return key_data

@router.get("/calendar")
async def get_economic_calendar():
    """
    Vision 2.0: Institutional Economic Calendar.
    """
    # In a full impl, we'd use a macro provider like TradingEconomics or Investing.com
    return [
        {"time": "11:00 AM", "country": "IN", "event": "RBI Monetary Policy Meeting", "impact": "CRITICAL", "forecast": "6.50%", "actual": "6.50%"},
        {"time": "2:30 PM", "country": "EU", "event": "ECB Press Conference", "impact": "HIGH", "forecast": "---", "actual": "---"},
        {"time": "6:00 PM", "country": "US", "event": "Non-Farm Payrolls", "impact": "HIGH", "forecast": "180K", "actual": "---"}
    ]
