import os
import sys
import asyncio
import json
import uuid
from datetime import datetime, timedelta
from dotenv import load_dotenv

# Add project root to path
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '../../')))
load_dotenv('backend/.env')

from backend.core.postgres import SessionLocal, LiveSignalDB, StockDB

async def populate():
    print("[*] Populating Master Signal Grid (Equity, Futures, Options)...")

    db = SessionLocal()
    try:
        # Forensic Cleanup: Clear existing live signals generated by this script
        print("[*] Performing segment cleanup before population...")
        db.query(LiveSignalDB).filter(LiveSignalDB.id.like('live_%')).delete(synchronize_session=False)

        now = datetime.utcnow()

        # 1. Clean up stale active signals to avoid clutter (Optional, but helps audit)
        # db.query(LiveSignalDB).filter(LiveSignalDB.status.in_(['ACTIVE', 'WAITING_FOR_ENTRY', 'ENTRY_TRIGGERED'])).delete()

        signals = []

        # --- EQUITY ---
        equity_symbols = ["RELIANCE", "TCS", "INFY", "HDFCBANK", "ICICIBANK", "SBIN", "BHARTIARTL", "AXISBANK", "LT", "ITC", "KOTAKBANK", "ESCORTS"]
        for i, sym in enumerate(equity_symbols):
            signals.append(LiveSignalDB(
                id=f"live_eq_{sym}_{i}", symbol=sym, timestamp=now - timedelta(minutes=i*10),
                rating="BUY" if i % 3 != 0 else "STRONG BUY", direction="LONG", conviction=75 + (i % 20),
                entry_price=1000 + i*50, target_price=1100 + i*50, stop_loss_price=950 + i*50,
                timeframe="SWING", status="ACTIVE", asset_class="EQUITY",
                model_version="TradeMind Core v2.2",
                events=json.dumps([{"type": "GENERATED", "timestamp": now.isoformat()}])
            ))

        # --- FUTURES ---
        futures_setups = [
            ("NIFTY", 24800, 25200, 24650),
            ("BANKNIFTY", 52500, 53500, 52200),
            ("RELIANCE", 3020, 3150, 2980),
            ("TCS", 4550, 4700, 4480),
            ("INFY", 1920, 2050, 1880)
        ]
        for i, (sym, entry, target, stop) in enumerate(futures_setups):
            signals.append(LiveSignalDB(
                id=f"live_fut_{sym}_{i}", symbol=sym, timestamp=now - timedelta(minutes=i*5),
                rating="BUY", direction="LONG", conviction=80 + i,
                entry_price=float(entry), target_price=float(target), stop_loss_price=float(stop),
                timeframe="INTRADAY", status="ACTIVE", asset_class="FUTURES",
                underlying_symbol=sym, expiry=now + timedelta(days=10),
                model_version="TradeMind F&O v1.1",
                events=json.dumps([{"type": "GENERATED", "timestamp": now.isoformat()}])
            ))

        # --- OPTIONS ---
        options_setups = [
            ("NIFTY", 25000, "CE", 145, 250, 90),
            ("RELIANCE", 3100, "CE", 42, 85, 25),
            ("HDFCBANK", 1600, "PE", 28, 60, 15),
            ("TCS", 4600, "CE", 110, 180, 70),
            ("SBIN", 850, "CE", 15, 35, 8)
        ]
        for i, (sym, strike, opt_type, entry, target, stop) in enumerate(options_setups):
            signals.append(LiveSignalDB(
                id=f"live_opt_{sym}_{strike}_{i}", symbol=sym, timestamp=now - timedelta(minutes=i*2),
                rating="BUY" if opt_type == "CE" else "SELL", direction="LONG", conviction=85 - i,
                entry_price=float(entry), target_price=float(target), stop_loss_price=float(stop),
                timeframe="SWING", status="ACTIVE", asset_class="OPTIONS",
                underlying_symbol=sym, strike=float(strike), option_type=opt_type, expiry=now + timedelta(days=10),
                model_version="TradeMind F&O v1.1",
                events=json.dumps([{"type": "GENERATED", "timestamp": now.isoformat()}])
            ))

        for s in signals:
            existing = db.query(LiveSignalDB).filter(LiveSignalDB.id == s.id).first()
            if not existing:
                db.add(s)

        db.commit()
        print(f"[+] Successfully populated {len(signals)} signals.")

    except Exception as e:
        print(f"[-] Error: {e}")
        db.rollback()
    finally:
        db.close()

if __name__ == "__main__":
    asyncio.run(populate())
