import { Box, Typography, Paper, Grid, Stack, Button, alpha, Divider } from '@mui/material';
import { CheckCircle2, Zap, ShieldCheck, Sparkles } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { MONO_FONT, COLORS, GLASS_PANEL_STYLE, HERO_BANNER_STYLE, GRADIENT_ACCENT_BAR } from '../theme/institutionalTheme';

export default function Pricing() {
  const navigate = useNavigate();

  return (
    <Box sx={{ pb: { xs: 14, md: 10 }, width: '100%', maxWidth: 1280, mx: 'auto', px: { xs: 2, sm: 4, lg: 6 }, pt: 4, color: 'white', boxSizing: 'border-box' }}>
      {/* Hero Header */}
      <Box sx={{ ...HERO_BANNER_STYLE, mb: 6, textAlign: 'center' }}>
        <Box sx={{ position: 'absolute', top: 0, left: 0, right: 0, ...GRADIENT_ACCENT_BAR }} />
        <Typography variant="h3" sx={{ fontWeight: 950, letterSpacing: -1.5, mb: 1, fontFamily: MONO_FONT, color: '#fff' }}>
          PRICING & SUBSCRIPTION TIERS
        </Typography>
        <Typography variant="h6" sx={{ color: COLORS.cyan, fontWeight: 800, letterSpacing: 1, fontFamily: MONO_FONT }}>
          SELECT YOUR QUANTITATIVE INTELLIGENCE HORIZON
        </Typography>
      </Box>

      <Grid container spacing={4} alignItems="stretch">
        <Grid item xs={12} md={4}>
           <PriceTier
             title="FREE"
             price="₹0"
             subtitle="Research Baseline Access"
             features={[
               "Active Opportunity Scanner",
               "Limited Signal Replay",
               "Historical Outcome Ledger",
               "Basic Market Regime Monitor"
             ]}
             cta="Get Started Free"
             onClick={() => navigate('/login')}
           />
        </Grid>
        <Grid item xs={12} md={4}>
           <PriceTier
             title="PRO"
             price="₹2,499"
             period="/ mo"
             highlighted
             subtitle="Institutional Intelligence & Forensics"
             features={[
               "Full Signal Detail Terminal Access",
               "Advanced Evidence Forensic Audit",
               "Unlimited Signal Replay & Timelines",
               "Multi-Signal Comparison Mode",
               "Priority Real-Time Data Pipeline"
             ]}
             cta="Upgrade To Pro"
             onClick={() => navigate('/checkout/pro')}
           />
        </Grid>
        <Grid item xs={12} md={4}>
           <PriceTier
             title="ALPHA"
             price="₹7,999"
             period="/ mo"
             subtitle="Advanced Institutional Quant"
             features={[
               "Everything in Pro Tier",
               "Custom Prediction API Endpoints",
               "Priority Model Retraining Runs",
               "Whitelabel Forensic Reporting",
               "Dedicated Quant Analyst Support"
             ]}
             cta="Subscribe Alpha"
             onClick={() => navigate('/checkout/alpha')}
           />
        </Grid>
      </Grid>

      <Box sx={{ mt: 12, textAlign: 'center' }}>
         <Typography variant="h5" sx={{ fontWeight: 950, mb: 4, letterSpacing: -0.5, fontFamily: MONO_FONT }}>Frequently Asked Questions</Typography>
         <Grid container spacing={4} sx={{ textAlign: 'left' }}>
            <Grid item xs={12} md={6}>
               <Paper sx={{ ...GLASS_PANEL_STYLE, p: 3.5 }}>
                  <Typography variant="subtitle2" sx={{ fontWeight: 950, mb: 1, color: COLORS.cyan, display: 'flex', alignItems: 'center', gap: 1, fontFamily: MONO_FONT }}>
                     <ShieldCheck size={16} /> Does TradeMind AI execute orders on my broker?
                  </Typography>
                  <Typography variant="body2" sx={{ color: COLORS.slateText, lineHeight: 1.6, fontWeight: 500 }}>
                     No. TradeMind AI is a pure signal intelligence and quantitative terminal. We do not execute orders on your behalf. All generated signals serve as institutional decision support.
                  </Typography>
               </Paper>
            </Grid>
            <Grid item xs={12} md={6}>
               <Paper sx={{ ...GLASS_PANEL_STYLE, p: 3.5 }}>
                  <Typography variant="subtitle2" sx={{ fontWeight: 950, mb: 1, color: COLORS.cyan, display: 'flex', alignItems: 'center', gap: 1, fontFamily: MONO_FONT }}>
                     <Sparkles size={16} /> How is the Win Rate verified?
                  </Typography>
                  <Typography variant="body2" sx={{ color: COLORS.slateText, lineHeight: 1.6, fontWeight: 500 }}>
                     Every signal generated by Strategy V3.3 is timestamped and recorded in our immutable Neon ledger before market movement occurs. Outcomes are validated automatically against NSE Spot closing nodes.
                  </Typography>
               </Paper>
            </Grid>
         </Grid>
      </Box>

      <Box sx={{ mt: 8, p: 4, bgcolor: alpha(COLORS.green, 0.05), borderRadius: 3, border: `1px dashed ${COLORS.green}`, textAlign: 'center' }}>
         <Typography variant="h6" sx={{ fontWeight: 950, color: 'white', mb: 1, fontFamily: MONO_FONT }}>READY TO DISCOVER THE FORENSICS BEHIND EVERY SIGNAL?</Typography>
         <Button
           variant="contained"
           size="large"
           startIcon={<Zap size={18} />}
           onClick={() => navigate('/login')}
           sx={{ mt: 2, px: 6, py: 1.5, fontWeight: 950, bgcolor: COLORS.green, color: '#000', fontFamily: MONO_FONT, '&:hover': { bgcolor: '#059669' } }}
         >
           JOIN TRADEMIND TERMINAL
         </Button>
      </Box>
    </Box>
  );
}

function PriceTier({ title, price, period = "", subtitle, features, cta, onClick, highlighted = false }: any) {
    return (
        <Paper sx={{
            ...GLASS_PANEL_STYLE,
            p: 4.5,
            height: '100%',
            borderColor: highlighted ? COLORS.cyan : COLORS.borderLight,
            borderWidth: highlighted ? 2 : 1,
            display: 'flex',
            flexDirection: 'column',
            position: 'relative',
            boxShadow: highlighted ? '0 15px 35px -10px rgba(0, 209, 255, 0.25)' : 'none',
            transition: 'all 0.2s ease-in-out',
            '&:hover': {
                transform: 'translateY(-4px)'
            }
        }}>
            {highlighted && (
                <Box sx={{
                    position: 'absolute', top: -14, left: '50%', transform: 'translateX(-50%)',
                    bgcolor: COLORS.cyan, color: '#000', px: 2, py: 0.3, borderRadius: 1,
                    fontSize: '0.65rem', fontWeight: 950, letterSpacing: 1, fontFamily: MONO_FONT, boxShadow: '0 4px 12px rgba(0,209,255,0.4)'
                }}>
                    POPULAR CHOICE
                </Box>
            )}
            <Typography variant="caption" sx={{ fontWeight: 950, color: COLORS.slateMuted, letterSpacing: 2, display: 'block', mb: 2, fontFamily: MONO_FONT }}>{title}</Typography>
            <Stack direction="row" alignItems="baseline" spacing={0.5} sx={{ mb: 1 }}>
                <Typography variant="h3" sx={{ fontWeight: 950, fontFamily: MONO_FONT }}>{price}</Typography>
                <Typography variant="caption" sx={{ color: COLORS.slateMuted, fontWeight: 800 }}>{period}</Typography>
            </Stack>
            <Typography variant="body2" sx={{ color: COLORS.cyan, fontWeight: 800, mb: 3 }}>{subtitle}</Typography>
            <Divider sx={{ mb: 3, opacity: 0.08 }} />
            <Stack spacing={2} sx={{ flexGrow: 1, mb: 5 }}>
                {features.map((f: string, i: number) => (
                    <Stack key={i} direction="row" spacing={1.5} alignItems="center">
                        <CheckCircle2 size={16} color={COLORS.green} />
                        <Typography variant="body2" sx={{ color: '#f8fafc', fontWeight: 600, fontSize: '0.85rem' }}>{f}</Typography>
                    </Stack>
                ))}
            </Stack>
            <Button
                fullWidth
                variant={highlighted ? "contained" : "outlined"}
                onClick={onClick}
                sx={{
                  py: 1.5,
                  fontWeight: 950,
                  borderRadius: 2,
                  fontFamily: MONO_FONT,
                  bgcolor: highlighted ? COLORS.cyan : 'transparent',
                  color: highlighted ? '#000' : '#fff',
                  borderColor: highlighted ? COLORS.cyan : COLORS.borderLight,
                  '&:hover': {
                    bgcolor: highlighted ? '#38bdf8' : 'rgba(255,255,255,0.05)'
                  }
                }}
            >
                {cta}
            </Button>
        </Paper>
    );
}
