import { Box, Typography, Paper, Grid, Stack, Button, alpha, Divider } from '@mui/material';
import { CheckCircle2 } from 'lucide-react';
import { useNavigate } from 'react-router-dom';

export default function Pricing() {
  const navigate = useNavigate();

  return (
    <Box sx={{ pb: 10, maxWidth: 1000, mx: 'auto', p: 4, color: 'white' }}>
      <Box sx={{ mb: 10, textAlign: 'center' }}>
        <Typography variant="h3" sx={{ fontWeight: 950, letterSpacing: -2, mb: 2 }}>PRICING</Typography>
        <Typography variant="h6" sx={{ color: '#00D1FF', fontWeight: 800 }}>CHOOSE YOUR INTELLIGENCE TIER</Typography>
      </Box>

      <Grid container spacing={4} alignItems="stretch">
        <Grid item xs={12} md={4}>
           <PriceTier
             title="FREE"
             price="₹0"
             subtitle="Research Baseline"
             features={[
               "Active Opportunity Scanner",
               "Limited Signal Replay",
               "Historical Outcome Ledger",
               "Basic Market Regime"
             ]}
             cta="Get Started"
             onClick={() => navigate('/login')}
           />
        </Grid>
        <Grid item xs={12} md={4}>
           <PriceTier
             title="PRO"
             price="₹2,499"
             period="/ mo"
             highlighted
             subtitle="Institutional Intelligence"
             features={[
               "Full Signal Detail Terminal",
               "Advanced Evidence Forensic",
               "Unlimited Signal Replay",
               "Comparison Mode",
               "120h Freshness Priority"
             ]}
             cta="Go Pro"
             onClick={() => navigate('/checkout/pro')}
           />
        </Grid>
        <Grid item xs={12} md={4}>
           <PriceTier
             title="ALPHA"
             price="₹7,999"
             period="/ mo"
             subtitle="Advanced Quantitative"
             features={[
               "Everything in Pro",
               "Custom Prediction API",
               "Priority Model Retraining",
               "Whitelabel Reporting",
               "Dedicated Analyst Support"
             ]}
             cta="Contact Sales"
             onClick={() => navigate('/checkout/alpha')}
           />
        </Grid>
      </Grid>

      <Box sx={{ mt: 15, textAlign: 'center' }}>
         <Typography variant="h5" sx={{ fontWeight: 900, mb: 4 }}>Frequently Asked Questions</Typography>
         <Grid container spacing={4} sx={{ textAlign: 'left' }}>
            <Grid item xs={12} md={6}>
               <Typography variant="subtitle2" sx={{ fontWeight: 950, mb: 2, color: '#00D1FF' }}>Does TradeMind AI execute trades?</Typography>
               <Typography variant="body2" sx={{ color: 'slategray', mb: 4 }}>
                  No. TradeMind AI is a signal intelligence and research terminal. We do not execute orders on your behalf. All signals are for informational purposes only.
               </Typography>
            </Grid>
            <Grid item xs={12} md={6}>
               <Typography variant="subtitle2" sx={{ fontWeight: 950, mb: 2, color: '#00D1FF' }}>What is the 'Observed Win Rate'?</Typography>
               <Typography variant="body2" sx={{ color: 'slategray', mb: 4 }}>
                  It is the actual success rate of the signals generated by our models in a shadow execution environment. Every signal is recorded in real-time before the outcome is known.
               </Typography>
            </Grid>
         </Grid>
      </Box>

      <Box sx={{ mt: 10, p: 4, bgcolor: alpha('#10b981', 0.05), borderRadius: 1, border: '1px dashed #10b981', textAlign: 'center' }}>
         <Typography variant="h6" sx={{ fontWeight: 950, color: 'white', mb: 1 }}>READY TO DISCOVER THE STORY BEHIND EVERY SIGNAL?</Typography>
         <Button
           variant="contained"
           size="large"
           onClick={() => navigate('/login')}
           sx={{ mt: 2, px: 8, py: 1.5, fontWeight: 950 }}
         >
           JOIN TRADEMIND AI
         </Button>
      </Box>
    </Box>
  );
}

function PriceTier({ title, price, period = "", subtitle, features, cta, onClick, highlighted = false }: any) {
    return (
        <Paper sx={{
            p: 5,
            height: '100%',
            bgcolor: highlighted ? alpha('#00D1FF', 0.03) : '#0f172a',
            border: highlighted ? '2px solid #00D1FF' : '1px solid rgba(255,255,255,0.05)',
            display: 'flex',
            flexDirection: 'column',
            position: 'relative'
        }}>
            {highlighted && (
                <Box sx={{
                    position: 'absolute', top: -12, left: '50%', transform: 'translateX(-50%)',
                    bgcolor: '#00D1FF', color: '#000', px: 2, py: 0.2, borderRadius: 0.5,
                    fontSize: '0.6rem', fontWeight: 950, letterSpacing: 1
                }}>
                    MOST POPULAR
                </Box>
            )}
            <Typography variant="caption" sx={{ fontWeight: 950, color: 'slategray', letterSpacing: 2, display: 'block', mb: 2 }}>{title}</Typography>
            <Stack direction="row" alignItems="baseline" spacing={0.5} sx={{ mb: 1 }}>
                <Typography variant="h3" sx={{ fontWeight: 950 }}>{price}</Typography>
                <Typography variant="caption" sx={{ color: 'slategray', fontWeight: 800 }}>{period}</Typography>
            </Stack>
            <Typography variant="body2" sx={{ color: '#00D1FF', fontWeight: 800, mb: 4 }}>{subtitle}</Typography>
            <Divider sx={{ mb: 4, opacity: 0.05 }} />
            <Stack spacing={2} sx={{ flexGrow: 1, mb: 6 }}>
                {features.map((f: string, i: number) => (
                    <Stack key={i} direction="row" spacing={1.5} alignItems="center">
                        <CheckCircle2 size={16} color="#10b981" />
                        <Typography variant="body2" sx={{ color: 'white', fontWeight: 600, fontSize: '0.85rem' }}>{f}</Typography>
                    </Stack>
                ))}
            </Stack>
            <Button
                fullWidth
                variant={highlighted ? "contained" : "outlined"}
                onClick={onClick}
                sx={{ py: 1.5, fontWeight: 950, borderColor: 'rgba(255,255,255,0.1)', color: highlighted ? '#000' : '#fff' }}
            >
                {cta}
            </Button>
        </Paper>
    );
}
