import { Box, Typography, Paper, Stack, Divider } from '@mui/material';

export default function RiskDisclosure() {
  return (
    <Box sx={{ pb: 10, maxWidth: 900, mx: 'auto', p: 4, color: 'white' }}>
      <Box sx={{ mb: 8, textAlign: 'center' }}>
        <Typography variant="h3" sx={{ fontWeight: 950, letterSpacing: -2, mb: 2 }}>RISK DISCLOSURE</Typography>
        <Typography variant="h6" sx={{ color: '#ef4444', fontWeight: 800 }}>MANDATORY SAFETY & REGULATORY NOTICE</Typography>
      </Box>

      <Stack spacing={6}>
         <section>
            <Typography variant="h5" sx={{ fontWeight: 900, mb: 3 }}>1. Nature of Service</Typography>
            <Typography sx={{ color: 'slategray', lineHeight: 1.8 }}>
               TradeMind AI is a financial intelligence and quantitative research terminal. We provide machine-generated
               market signals and evidence-based analysis for Indian equities. **TradeMind AI is not a SEBI-registered
               Investment Adviser or Research Analyst.** All information provided is for educational and research
               purposes only.
            </Typography>
         </section>

         <section>
            <Typography variant="h5" sx={{ fontWeight: 900, mb: 3 }}>2. Market Risk</Typography>
            <Typography sx={{ color: 'slategray', lineHeight: 1.8 }}>
               Investing in the stock market involves significant risk of loss. Prices can be volatile and are influenced
               by numerous factors beyond the control of any model. You should never invest money that you cannot
               afford to lose.
            </Typography>
         </section>

         <section>
            <Typography variant="h5" sx={{ fontWeight: 900, mb: 3 }}>3. Model & AI Risk</Typography>
            <Typography sx={{ color: 'slategray', lineHeight: 1.8 }}>
               The signals generated by TradeMind AI are the output of complex machine-learning models (Strategy V2.2).
               While these models are validated against historical data, **past performance is not a guarantee of future
               results.** Algorithm failures, data gaps, and changing market regimes can lead to incorrect predictions.
            </Typography>
         </section>

         <section>
            <Typography variant="h5" sx={{ fontWeight: 900, mb: 3 }}>4. Real Trading Disabled</Typography>
            <Paper sx={{ p: 4, bgcolor: 'rgba(239, 68, 68, 0.05)', border: '1px solid rgba(239, 68, 68, 0.2)' }}>
               <Typography variant="body1" sx={{ color: '#ef4444', fontWeight: 800, mb: 2, textTransform: 'uppercase' }}>Shadow Mode Enforcement</Typography>
               <Typography sx={{ color: 'slategray', lineHeight: 1.8 }}>
                  TradeMind AI currently operates in **SHADOW MODE ONLY**. The platform does not execute real trades.
                  Broker integration is disabled, and no real capital is deployed. Any profit/loss shown is
                  **unrealized and theoretical.**
               </Typography>
            </Paper>
         </section>

         <section>
            <Typography variant="h5" sx={{ fontWeight: 900, mb: 3 }}>5. No Professional Advice</Typography>
            <Typography sx={{ color: 'slategray', lineHeight: 1.8 }}>
               The contents of this terminal do not constitute financial, legal, or tax advice. You are responsible
               for your own investment decisions. We recommend consulting with a qualified SEBI-registered
               professional before making any real-world investments.
            </Typography>
         </section>

         <Divider sx={{ opacity: 0.1 }} />

         <Typography variant="caption" sx={{ color: 'slategray', textAlign: 'center', display: 'block' }}>
            Last Updated: September 17, 2026 • TradeMind AI Compliance Framework
         </Typography>
      </Stack>
    </Box>
  );
}
